PERMISSIONS = [
    # ---- GLOBAL ----
    ('users.read', 'View users', 'global'),
    ('users.write', 'Create and update users', 'global'),
    ('group_memberships.read', 'View user groups', 'global'),
    ('group_memberships.write', 'Create and update user groups', 'global'),
    ('clients.read', 'View clients', 'global'),
    ('clients.write', 'Create and update clients', 'global'),
    ('projects.write', 'Create projects', 'global'),
    ('test_cases.read', 'View test cases', 'global'),
    ('test_cases.write', 'Create and update test cases', 'global'),
    ('test_case_versions.read', 'View test case versions', 'global'),
    ('test_case_versions.write', 'Create and update test case versions', 'global'),
    ('test_suites.read', 'View test suites', 'global'),
    ('test_suites.write', 'Create and update test suites', 'global'),
    ('suitcases.read', 'View suitcases', 'global'),
    ('suitcases.write', 'Create and update suitcases', 'global'),
    ('scenarios.read', 'View scenarios', 'global'),
    ('scenarios.write', 'Create and update scenarios', 'global'),
    ('statuses.read', 'View statuses', 'global'),
    ('statuses.write', 'Create and update statuses', 'global'),
    ('status_sets.read', 'View status sets', 'global'),
    ('status_sets.write', 'Create and update status sets', 'global'),
    ('user_groups.read', 'View user groups', 'global'),
    ('user_groups.write', 'Create and update user groups', 'global'),
    ('relation_types.read', 'View relation types', 'global'),
    ('relation_types.write', 'Create and update relation types', 'global'),
    ('resolutions.read', 'View resolutions', 'global'),
    ('resolutions.write', 'Create and update resolutions', 'global'),
    ('permissions.read', 'View permissions', 'global'),
    ('permissions.write', 'Create and delete permissions', 'global'),
    ('permissions.delete', 'Delete permissions', 'global'),
    ('group_permissions.read', 'View group-permission assignments', 'global'),
    ('group_permissions.write', 'Assign and remove group permissions', 'global'),
    ('test_case_restrictions.write', 'Restrict a test case to specific projects', 'global'),
    ('test_suite_restrictions.write', 'Restrict a test suite to specific projects', 'global'),
    ('sessions.read', 'View active sessions', 'global'),
    ('sessions.delete', 'Revoke a session', 'global'),

    # ---- LOCAL (project-scoped) ----
    ('projects.read', 'View a project', 'local'),
    ('project_members.read', 'View project members', 'local'),
    ('project_members.write', 'Add/remove project members', 'local'),
    ('devices.read', 'View devices', 'local'),
    ('devices.write', 'Create and update devices', 'local'),
    ('runs.read', 'View runs', 'local'),
    ('runs.write', 'Create and update runs', 'local'),
    ('executions.read', 'View executions', 'local'),
    ('executions.write', 'Update executions (status/result/attachment)', 'local'),
    ('executions.create_matrix', 'Create bulk executions from test suite x devices', 'local'),
    ('executions.retest', 'Create a retest execution as a copy', 'local'),
    ('executions.delete', 'Delete an execution', 'local'),
    ('execution_relationships.read', 'View execution relationships', 'local'),
    ('execution_relationships.write', 'Create and update execution relationships', 'local'),
    ('attachments.read', 'View attachments', 'local'),
    ('attachments.write', 'Upload and edit attachments', 'local'),
]