PERMISSIONS = [
    ("users.read", "View users"),
    ("users.write", "Create and update users"),
    ("group_memberships.read", "View user groups"),
    ("group_memberships.write", "Create and update user groups"),
    ("clients.read", "View clients"),
    ("clients.write", "Create and update clients"),
    ("projects.read", "View projects"),
    ("projects.write", "Create and update projects"),
    ("devices.read", "View devices"),
    ("devices.write", "Create and update devices"),
    ("runs.read", "View runs"),
    ("runs.write", "Create and update runs"),
    ("test_cases.read", "View test cases"),
    ("test_cases.write", "Create and update test cases"),
    ("test_case_versions.read", "View test case versions"),
    ("test_case_versions.write", "Create and update test case versions"),
    ("test_suites.read", "View test suites"),
    ("test_suites.write", "Create and update test suites"),
    ("suitcases.read", "View suitcases"),
    ("suitcases.write", "Create and update suitcases"),
    ("executions.read", "View executions"),
    ("executions.write", "Create and update executions"),
    ("execution_relationships.read", "View execution relationships"),
    ("execution_relationships.write", "Create and update execution relationships"),
    ("attachments.read", "View attachments"),
    ("attachments.write", "Create and update attachments"),
    ("scenarios.read", "View scenarios"),
    ("scenarios.write", "Create and update scenarios"),
    ("statuses.read", "View statuses"),
    ("statuses.write", "Create and update statuses"),
    ("status_sets.read", "View status sets"),
    ("status_sets.write", "Create and update status sets"),
    ("user_groups.read", "View user groups"),
    ("user_groups.write", "Create and update user groups"),
    ("relation_types.read", "View relation types"),
    ("relation_types.write", "Create and update relation types"),
    ("resolutions.read", "View resolutions"),
    ("resolutions.write", "Create and update resolutions"),
    ("permissions.read", "View permissions"),
    ("permissions.write", "Create and delete permissions"),
    ("permissions.delete", "Delete permissions"),
    ("group_permissions.read", "View group-permission assignments"),
    ("group_permissions.write", "Assign and remove group permissions"),
]