"""forgot to add a few new tables to the init. Adding them now, and creating new migration

Revision ID: 02fb4d79a867
Revises: eaaaf048ce14
Create Date: 2026-07-16 16:54:49.940877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fb4d79a867'
down_revision: Union[str, Sequence[str], None] = 'eaaaf048ce14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_index('group_member_group_idx', 'groups_members', ['group_id'], unique=False)
    op.create_index('group_member_user_idx', 'groups_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('group_member_user_idx', table_name='groups_members')
    op.drop_index('group_member_group_idx', table_name='groups_members')
    op.drop_table('groups_members')
    # ### end Alembic commands ###
