"""added further permissions schema and further permission groupings and removed the user type completely

Revision ID: ab7496403074
Revises: 02fb4d79a867
Create Date: 2026-07-23 17:19:53.272132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7496403074'
down_revision: Union[str, Sequence[str], None] = '02fb4d79a867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'project_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table(
        'project_role_permissions',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id']),
        sa.ForeignKeyConstraint(['role_id'], ['project_roles.id']),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )

    op.create_index(
        'project_role_permissions_permission_idx',
        'project_role_permissions',
        ['permission_id'],
        unique=False
    )

    op.create_index(
        'project_role_permissions_role_idx',
        'project_role_permissions',
        ['role_id'],
        unique=False
    )

    op.create_table(
        'project_members',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['role_id'], ['project_roles.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('project_id', 'user_id')
    )

    op.create_index(
        'project_member_project_idx',
        'project_members',
        ['project_id'],
        unique=False
    )

    op.create_index(
        'project_member_role_idx',
        'project_members',
        ['role_id'],
        unique=False
    )

    op.create_index(
        'project_member_user_idx',
        'project_members',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'test_case_restrictions',
        sa.Column('test_case_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id']),
        sa.PrimaryKeyConstraint('test_case_id', 'project_id')
    )

    op.create_index(
        'restriction_test_case_idx',
        'test_case_restrictions',
        ['test_case_id'],
        unique=False
    )

    op.create_index(
        'restriction_test_case_project_idx',
        'test_case_restrictions',
        ['project_id'],
        unique=False
    )

    op.create_table(
        'test_suite_restrictions',
        sa.Column('test_suite_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id']),
        sa.PrimaryKeyConstraint('test_suite_id', 'project_id')
    )

    op.create_index(
        'restriction_project_idx',
        'test_suite_restrictions',
        ['project_id'],
        unique=False
    )

    op.create_index(
        'restriction_test_suite_idx',
        'test_suite_restrictions',
        ['test_suite_id'],
        unique=False
    )

    # Add permissions scope safely
    op.add_column(
        'permissions',
        sa.Column('scope', sa.String(length=10), nullable=True)
    )

    op.execute(
        """
        UPDATE permissions
        SET scope = 'GLOBAL'
        WHERE scope IS NULL
        """
    )

    op.alter_column(
        'permissions',
        'scope',
        existing_type=sa.String(length=10),
        nullable=False
    )

    # Remove user_types dependency chain
    op.drop_index(
        op.f('user_user_type_idx'),
        table_name='users'
    )

    op.drop_constraint(
        op.f('users_user_type_id_fkey'),
        'users',
        type_='foreignkey'
    )

    op.drop_column(
        'users',
        'user_type_id'
    )

    op.drop_table(
        'user_types'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    # Restore user_types first because users depends on it
    op.create_table(
        'user_types',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            'id',
            name=op.f('user_types_pkey')
        ),
        sa.UniqueConstraint(
            'name',
            name=op.f('user_types_name_key'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'user_type_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        )
    )

    op.create_foreign_key(
        op.f('users_user_type_id_fkey'),
        'users',
        'user_types',
        ['user_type_id'],
        ['id']
    )

    op.create_index(
        op.f('user_user_type_idx'),
        'users',
        ['user_type_id'],
        unique=False
    )

    op.drop_column(
        'permissions',
        'scope'
    )

    op.drop_index(
        'restriction_test_suite_idx',
        table_name='test_suite_restrictions'
    )

    op.drop_index(
        'restriction_project_idx',
        table_name='test_suite_restrictions'
    )

    op.drop_table(
        'test_suite_restrictions'
    )

    op.drop_index(
        'restriction_test_case_project_idx',
        table_name='test_case_restrictions'
    )

    op.drop_index(
        'restriction_test_case_idx',
        table_name='test_case_restrictions'
    )

    op.drop_table(
        'test_case_restrictions'
    )

    op.drop_index(
        'project_member_user_idx',
        table_name='project_members'
    )

    op.drop_index(
        'project_member_role_idx',
        table_name='project_members'
    )

    op.drop_index(
        'project_member_project_idx',
        table_name='project_members'
    )

    op.drop_table(
        'project_members'
    )

    op.drop_index(
        'project_role_permissions_role_idx',
        table_name='project_role_permissions'
    )

    op.drop_index(
        'project_role_permissions_permission_idx',
        table_name='project_role_permissions'
    )

    op.drop_table(
        'project_role_permissions'
    )

    op.drop_table(
        'project_roles'
    )

    # ### end Alembic commands ###