"""init

Revision ID: b909fb864578
Revises: 
Create Date: 2026-02-04 17:25:57.974728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b909fb864578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_attachment_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('presentmon_version', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_attachment_id'], ['attachments.id'], use_alter=True),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('attachment_filename_idx', 'attachments', ['filename'], unique=False)
    op.create_index('attachment_parent_idx', 'attachments', ['parent_attachment_id'], unique=False)
    op.create_index('attachment_resolution_idx', 'attachments', ['resolution_id'], unique=False)
    op.create_index('attachment_uploaded_at_idx', 'attachments', ['uploaded_at'], unique=False)
    op.create_index('attachment_uploaded_by_idx', 'attachments', ['uploaded_by'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name_external', sa.String(), nullable=True),
    sa.Column('name_internal', sa.String(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('device_project_idx', 'devices', ['project_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_version_id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], use_alter=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], use_alter=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], use_alter=True),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], use_alter=True),
    sa.ForeignKeyConstraint(['test_case_version_id'], ['test_case_versions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'test_case_version_id', name='execution_run_version_unique')
    )
    op.create_index('execution_attachment_idx', 'executions', ['attachment_id'], unique=False)
    op.create_index('execution_device_idx', 'executions', ['device_id'], unique=False)
    op.create_index('execution_executor_idx', 'executions', ['executed_by'], unique=False)
    op.create_index('execution_run_idx', 'executions', ['run_id'], unique=False)
    op.create_index('execution_status_idx', 'executions', ['status_id'], unique=False)
    op.create_index('execution_test_case_version_idx', 'executions', ['test_case_version_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_name_idx', 'projects', ['name'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h', 'w', name='resolutions_hw_unique')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('session_token_idx', 'sessions', ['token'], unique=False)
    op.create_index('session_user_id_idx', 'sessions', ['user_id'], unique=False)
    op.create_table('status_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('user_group_created_by_idx', 'user_groups', ['created_by_id'], unique=False)
    op.create_index('user_group_owner_idx', 'user_groups', ['owner_id'], unique=False)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_suite_metadata', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('run_name_idx', 'runs', ['name'], unique=False)
    op.create_index('run_project_idx', 'runs', ['project_id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['status_set_id'], ['status_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('status_name_idx', 'statuses', ['name'], unique=False)
    op.create_index('status_status_set_idx', 'statuses', ['status_set_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['status_set_id'], ['status_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('test_case_scenario_idx', 'test_cases', ['scenario_id'], unique=False)
    op.create_index('test_case_status_set_idx', 'test_cases', ['status_set_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('user_user_group_idx', 'users', ['user_group_id'], unique=False)
    op.create_index('user_user_type_idx', 'users', ['user_type_id'], unique=False)
    op.create_table('suitcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'test_suite_id')
    )
    op.create_index('suitcase_test_case_idx', 'suitcases', ['test_case_id'], unique=False)
    op.create_index('suitcase_test_suite_idx', 'suitcases', ['test_suite_id'], unique=False)
    op.create_table('test_case_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('release_ready', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'version', name='test_case_version_unique')
    )
    op.create_index('test_case_version_created_at_idx', 'test_case_versions', ['created_at'], unique=False)
    op.create_index('test_case_version_created_by_idx', 'test_case_versions', ['created_by'], unique=False)
    op.create_index('test_case_version_test_case_idx', 'test_case_versions', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('test_case_version_test_case_idx', table_name='test_case_versions')
    op.drop_index('test_case_version_created_by_idx', table_name='test_case_versions')
    op.drop_index('test_case_version_created_at_idx', table_name='test_case_versions')
    op.drop_table('test_case_versions')
    op.drop_index('suitcase_test_suite_idx', table_name='suitcases')
    op.drop_index('suitcase_test_case_idx', table_name='suitcases')
    op.drop_table('suitcases')
    op.drop_index('user_user_type_idx', table_name='users')
    op.drop_index('user_user_group_idx', table_name='users')
    op.drop_table('users')
    op.drop_index('test_case_status_set_idx', table_name='test_cases')
    op.drop_index('test_case_scenario_idx', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('status_status_set_idx', table_name='statuses')
    op.drop_index('status_name_idx', table_name='statuses')
    op.drop_table('statuses')
    op.drop_index('run_project_idx', table_name='runs')
    op.drop_index('run_name_idx', table_name='runs')
    op.drop_table('runs')
    op.drop_table('user_types')
    op.drop_index('user_group_owner_idx', table_name='user_groups')
    op.drop_index('user_group_created_by_idx', table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_table('test_suites')
    op.drop_table('status_sets')
    op.drop_index('session_user_id_idx', table_name='sessions')
    op.drop_index('session_token_idx', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('scenarios')
    op.drop_table('resolutions')
    op.drop_index('project_name_idx', table_name='projects')
    op.drop_table('projects')
    op.drop_index('execution_test_case_version_idx', table_name='executions')
    op.drop_index('execution_status_idx', table_name='executions')
    op.drop_index('execution_run_idx', table_name='executions')
    op.drop_index('execution_executor_idx', table_name='executions')
    op.drop_index('execution_device_idx', table_name='executions')
    op.drop_index('execution_attachment_idx', table_name='executions')
    op.drop_table('executions')
    op.drop_index('device_project_idx', table_name='devices')
    op.drop_table('devices')
    op.drop_table('clients')
    op.drop_index('attachment_uploaded_by_idx', table_name='attachments')
    op.drop_index('attachment_uploaded_at_idx', table_name='attachments')
    op.drop_index('attachment_resolution_idx', table_name='attachments')
    op.drop_index('attachment_parent_idx', table_name='attachments')
    op.drop_index('attachment_filename_idx', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
