"""added groups and permissions and did a few tweaks to the model

Revision ID: eaaaf048ce14
Revises: 5e23ab1f56a7
Create Date: 2026-07-16 15:09:37.473513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaaf048ce14'
down_revision: Union[str, Sequence[str], None] = '5e23ab1f56a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('relation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_index('group_permissions_group_idx', 'group_permissions', ['group_id'], unique=False)
    op.create_index('group_permissions_permission_idx', 'group_permissions', ['permission_id'], unique=False)
    op.create_table('execution_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('related_execution_id', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['related_execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'related_execution_id', name='unique_execution_rel')
    )
    op.create_index('execution_relationship_execution_idx', 'execution_relationships', ['execution_id'], unique=False)
    op.create_index('execution_relationship_related_execution_idx', 'execution_relationships', ['related_execution_id'], unique=False)
    op.create_index('execution_relationship_relation_type_idx', 'execution_relationships', ['relation_type_id'], unique=False)
    op.add_column('executions', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('executions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('execution_assignee_idx', 'executions', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'executions', 'users', ['assigned_to'], ['id'])
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.alter_column('runs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('status_sets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('test_suites', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'user_groups', 'users', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.drop_index(op.f('user_user_group_idx'), table_name='users')
    op.drop_column('users', 'user_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_user_group_idx'), 'users', ['user_group_id'], unique=False)
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.alter_column('user_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('test_suites', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('status_sets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'owner_id')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_index('execution_assignee_idx', table_name='executions')
    op.drop_column('executions', 'started_at')
    op.drop_column('executions', 'assigned_to')
    op.drop_index('execution_relationship_relation_type_idx', table_name='execution_relationships')
    op.drop_index('execution_relationship_related_execution_idx', table_name='execution_relationships')
    op.drop_index('execution_relationship_execution_idx', table_name='execution_relationships')
    op.drop_table('execution_relationships')
    op.drop_index('group_permissions_permission_idx', table_name='group_permissions')
    op.drop_index('group_permissions_group_idx', table_name='group_permissions')
    op.drop_table('group_permissions')
    op.drop_table('relation_types')
    op.drop_table('permissions')
    # ### end Alembic commands ###
