"""changed the default user creation behavior to default to active=false

Revision ID: f6b0f943f3ca
Revises: 17d863001ca4
Create Date: 2026-07-29 18:10:43.588490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b0f943f3ca'
down_revision: Union[str, Sequence[str], None] = '17d863001ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
